<a href="https://colab.research.google.com/github/jethompson023/CS-491/blob/main/CS491Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Use NumPy to create a 10x10 array that contains the multiplication table. Here is what the values inside the array should look like. Show the code to create the array. Use the outer function to create the array.


In [ ]:
import numpy as np
import random

In [ ]:
table = np.outer(np.linspace(1,10,10), np.linspace(1,10,10))
print(table)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


2. Write code that selects the 4x4 array that is in the middle inside the big array. 


Answer:

Result should be:
[[16, 20, 24, 28],
[20, 25, 30, 35],
[24, 30, 36, 42],
[28, 35, 42, 49]]

In [ ]:
a = np.array([[16,20,24,28], [20,25,30,35]])
b = np.array([[24,30,36,42], [28,35,42,49]])
print(np.concatenate([a,b]))

[[16 20 24 28]
 [20 25 30 35]
 [24 30 36 42]
 [28 35 42 49]]


3. Create a 4x4 array that contains the numbers from 1 to 16. Use the arange and reshape functions. 

In [ ]:
a = np.arange(1,17).reshape((4,4))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


4. Consider the arrays from the last two questions. Create a new 4x4 array that has value of true if both values in the two arrays are even and false otherwise. Hint: use a vectorized custom function with two inputs.

In [ ]:
a = np.arange(1,17).reshape((4,4))
b = np.array([[16,20,24,28],
       [20,25,30,35],
       [24,30,36,42], 
       [28,35,42,49]])

def customFunc(a, b):
    #If a & b are even return 1 for "true" if not return "false""
    if ((a % 2) == 0) & ((b % 2) == 0):
        return True
    else:
        return False

result = np.vectorize(customFunc)(a,b)
print(result)

[[False  True False  True]
 [False False False False]
 [False  True False  True]
 [False False False False]]


5. Write code that returns the number of even numbers in the array from Q2.


In [ ]:
a = np.array([[16,20,24,28], [20,25,30,35]])
b = np.array([[24,30,36,42], [28,35,42,49]])
list = np.concatenate([a,b])

(list % 2 == 0).sum()

12

6. Write code the returns the square root of the numbers in the array from Q3.

In [ ]:
a = np.arange(1,17).reshape((4,4))

#find square root of items in the list
output = np.sqrt(a)

print(output)

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]


7. Write code that returns the array from Q1, where the numbers on the diagonal are incremented by 1. Do not explicitly enumerate all the elements on the diagonal.


In [ ]:
table_2 = table
np.fill_diagonal(table_2, table.diagonal() + 1)
print(table_2)

[[  4.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   7.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.  12.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  19.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  28.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  39.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  52.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  67.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  84.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 103.]]


8. Write code that shows the array from Q1 in reverse order. The first row should have the number 100, 90, ... 10. The second row should be the ninth row in the initial array in reverse order and so on.

In [ ]:
res = table[::-1] #reversing using list slicing
print(res)

[[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]]


9. Write code that creates a 10x10 array of random float numbers between 0.0 and 10.0. The numbers should appear in the array sorted in ascending order.

In [ ]:
randArray = np.random.uniform(size=(10,10), low = 0.0, high = 10.0)
print(randArray.round(2))

[[5.08 0.75 4.12 4.34 1.47 4.24 9.23 7.88 2.46 7.04]
 [7.   6.34 3.91 0.74 1.52 5.93 3.63 9.56 8.13 3.83]
 [8.33 1.72 3.67 0.41 2.72 4.77 3.11 5.78 2.78 7.18]
 [9.49 8.61 6.52 2.39 9.03 0.89 8.43 8.77 3.65 8.44]
 [9.57 5.66 1.18 4.11 8.36 0.68 0.27 4.94 5.53 8.9 ]
 [3.2  5.09 1.95 1.46 7.85 3.53 5.06 0.38 0.38 3.92]
 [2.98 2.02 5.41 8.   9.74 5.51 8.6  9.85 5.77 9.31]
 [9.35 0.34 0.06 6.64 1.17 6.76 5.11 2.3  9.89 1.78]
 [5.87 7.21 2.65 2.58 4.52 3.29 4.28 9.93 8.53 8.04]
 [1.89 4.41 1.02 3.96 0.69 4.85 4.8  4.6  3.39 7.04]]


10. Write code that creates one-dimensional array of 10 elements. The ith element should be the average of the numbers in the ith row of the array from Q1.

In [ ]:
x = np.ones((10, 10))
for i in range(1,11):
  for j in range(1,11):
    x[i-1,j-1]=i*j
print(x)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


11[4]. Write a method that performs merge sort. Use partition, split, recursion, and the hstack method. 

In [ ]:
def mergeSort(myArray):
  if len(myArray) // 2:
    middle = len(myArray) // 2
    left = myArray[:middle]
    right = myArray[middle:]

    #Create your recurrsive call for both sides
    mergeSort(left)
    mergeSort(right)

    #Create an interators for the halves and for the main list
    i = 0
    j = 0
    k = 0

    while i < len(left) and j < len(right):
        if left[i] < right[j]:
          myArray[k] = left[i]
          i += 1
        else:
          myArray[k] = right[j]
          j += 1
        
        #Move k to the next slot
        k += 1
      
    #Join both the left and the right side
    while i < len(left):
      myArray[k] = left[i]
      i += 1
      k += 1
      
    while j < len(right):
      myArray[k] = right[j]
      j += 1
      k += 1
  
#Create a method to print our array
def printList(myArray):
	for i in range(len(myArray)):
		print(myArray[i], end=" ")
	print()
 
#Create Driver to make our array and perform partition
if __name__ == '__main__':
    myArray = [12, 11, 13, 5, 6, 7]
    print("First Array:")
    printList(myArray)
    
    #Perform the MergeSort
    mergeSort(myArray)
    print("Sorted array: ")
    printList(myArray)

    #Perform a Partition
    myArrayPart = np.partition(myArray, 3)
    print("Partition array: ")
    printList(myArrayPart)

    #Split the array 
    myArraySplit = np.array_split(myArrayPart, 2)
    print("Split array: ")
    printList(myArraySplit)

    #Perform the hstack 
    in_arr1 = myArraySplit[0]
    in_arr2 = myArraySplit[1]
    stack = np.hstack((in_arr1, in_arr2))
    print("hstack Array: ")
    printList(stack)

First Array:
12 11 13 5 6 7 
Sorted array: 
5 6 7 11 12 13 
Partition array: 
6 5 7 11 12 13 
Split array: 
[6 5 7] [11 12 13] 
hstack Array: 
6 5 7 11 12 13 
